e_commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (home_page, 
                    about_page, 
                    contact_page, 
                    login_page, 
                    logout_page,
                    register_page
)

urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('search/', include("search.urls", namespace="search")),
    path('products/', include("products.urls", namespace="products")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

app_name = "products"

from .views import (
                        ProductListView, 
                        ProductDetailSlugView,
                    )

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='detail')
]

search/urls.py
from django.urls import path

app_name = "search"

from .views import (
                        SearchProductView, 
                    )
urlpatterns = [
    path('', SearchProductView.as_view(), name='query'),
]

templates/base/content_body.html
{% load static %}
<ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab"  href="#img1">Computadores</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab"  href="#img2">Notbooks</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab"  href="#img3">Acessórios</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab"  href="#img4">Celulares</a>
      </li>
     
   
  </ul>


  <div class="tab-content">
    <div class="tab-pane container active" id="img1">
        <br>
        <img src="{% static 'img/pc2.jpg' %}" class="rounded float-right" alt="..." style="width:30%">
   
        <img src="{% static 'img/pc3.jpg' %}" class="rounded float-left" alt="..." style="width:30%">

        <div class="tab-pane container " id="img1">
            <button type="button" class="btn btn-outline-primary float-left">Comprar</button>
            <button type="button" class="btn btn-outline-primary float-right">Comprar</button>
        </div>
      
    </div>
    
    <div class="tab-pane container fade" id="img2">
        <br>
        <img src="{% static 'img/nt1.jpg' %}" class="rounded float-right" alt="..." style="width:30%">
        <img src="{% static 'img/nt3.jpg' %}" class="rounded float-left" alt="..." style="width:30%">
        <div class="tab-pane container " id="img2">
            <button type="button" class="btn btn-outline-primary float-left">Comprar</button>
            <button type="button" class="btn btn-outline-primary float-right">Comprar</button>
        </div>
    </div>
    
    <div class="tab-pane container fade" id="img3">
        <br>
        <img src="{% static 'img/teclado2.jpg' %}" class="rounded float-right" alt="..." style="width:30%">
        <img src="{% static 'img/i7.png' %}" class="rounded float-left" alt="..." style="width:30%">
        <div class="tab-pane container " id="img3">
            <button type="button" class="btn btn-outline-primary float-left">Comprar</button>
            <button type="button" class="btn btn-outline-primary float-right">Comprar</button>
        </div>
  
    </div>
    
    <div class="tab-pane container fade" id="img4">
        <br>
        <img src="{% static 'img/iPhone1.jpg' %}" class="rounded float-right" alt="..." style="width:30%">
        <img src="{% static 'img/xiaomi1.jpg' %}" class="rounded float-left" alt="..." style="width:30%">
        <div class="tab-pane container" id="img4">
            <button type="button" class="btn btn-outline-primary float-left">Comprar</button>
            <button type="button" class="btn btn-outline-primary float-right">Comprar</button>
        </div>
  
    </div>
    
  </div>

templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class='container'>
    <a class="navbar-brand" href="{{ home_url }}">
      <img src="{% static 'img/cc.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      {% if nome_da_marca %} 
      {{ nome_da_marca }} 
      {% else %} C&oacute;digo Fluente eCommerce 
      {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %} active {% endif %}">
          <a class="nav-link font-weight-bold" href="{{ home_url }}">Home <span class="sr-only ">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == conntentact_url %} active {% endif %}">
          <a class="nav-link font-weight-bold" href="{{ contact_url }}">Contato</a>
        </li>
        <li class="nav-item {% if request.path == products_list_url %} active {% endif %}">
          <a class="nav-link font-weight-bold" href="{{ products_list_url }}">Produtos</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == login_url %} active {% endif %}"> 
          <a class="nav-link font-weight-bold" href="{{ logout_url }}">Logout</a> 
        </li>
        {% else %}
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
          <a class="nav-link font-weight-bold" href="{{ login_url }}">Login</a>
        </li>
        <li class="nav-item {% if request.path == register %} active {% endif %}"> 
          <a class="nav-link font-weight-bold" href="{{ register_url }}">Registrar-se</a> 
        </li>
      {% endif %}
        
      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>
  </div><!--fim container-->
</nav>